import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex justify-around items-center gap-4">
          <h1 className="text-2xl font-bold text-gray-800 dark:text-gray-200">
            
          </h1>
          <h1 className="text-2xl font-bold text-gray-800 dark:text-gray-200">
            Welcome to My Next.js App
          </h1>
          
        </header>
        {children}
      </body>
    </html>
  );
}
